// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://husynxczzvdcnsopcslq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh1c3lueGN6enZkY25zb3Bjc2xxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4Mzg0ODUsImV4cCI6MjA2NTQxNDQ4NX0.DAcaLWEoHz1LUXN9IseVu1z6mbqYSQbE1xKJ_QX-gfQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);